name: Auto Merge Dependabot Updates

on: pull_request_target

permissions:
  contents: read
  pull-requests: read

jobs:
  auto-merge-dependabot:
    runs-on: ubuntu-latest

    if: github.event.pull_request.user.login == 'dependabot[bot]'

    steps:
      - name: Fetch Dependabot metadata
        id: dependabot_metadata
        uses: dependabot/fetch-metadata@v2.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate GitHub CLI with a PAT
        run: echo "${{ secrets.DEPENDABOT_TOKEN }}" | gh auth login --with-token

      - name: Auto-merge minor and patch updates
        # Only merge if the PR is a minor or patch version update
        if: steps.dependabot_metadata.outputs.update-type == 'version-update:semver-minor' || steps.dependabot_metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
